INSERT INTO `sys_file_reference` (`uid`, `pid`, `tstamp`, `crdate`, `deleted`, `hidden`, `sys_language_uid`, `l10n_parent`, `uid_local`, `uid_foreign`, `tablenames`, `fieldname`, `sorting_foreign`, `title`, `description`, `alternative`, `link`, `crop`, `autoplay`, `l10n_state`) VALUES
(1, 1, 1541034240, 1541034240, 0, 0, 0, 0, 1, 1, 'tt_content', 'assets', 1, NULL, NULL, NULL, '', '{\"default\":{\"cropArea\":{\"height\":1,\"width\":0.999,\"x\":0,\"y\":0},\"selectedRatio\":\"NaN\",\"focusArea\":null}}', 0, NULL);
INSERT INTO `sys_file_reference` (`uid`, `pid`, `tstamp`, `crdate`, `deleted`, `hidden`, `sys_language_uid`, `l10n_parent`, `uid_local`, `uid_foreign`, `tablenames`, `fieldname`, `sorting_foreign`, `title`, `description`, `alternative`, `link`, `crop`, `autoplay`, `l10n_state`) VALUES
(2, 2, 1541034241, 1541034241, 0, 0, 0, 0, 1, 2, 'tt_content', 'assets', 1, NULL, NULL, NULL, '', '{\"default\":{\"cropArea\":{\"height\":1,\"width\":0.999,\"x\":0,\"y\":0},\"selectedRatio\":\"NaN\",\"focusArea\":null}}', 0, NULL);
INSERT INTO `sys_file_reference` (`uid`, `pid`, `tstamp`, `crdate`, `deleted`, `hidden`, `sys_language_uid`, `l10n_parent`, `uid_local`, `uid_foreign`, `tablenames`, `fieldname`, `sorting_foreign`, `title`, `description`, `alternative`, `link`, `crop`, `autoplay`, `l10n_state`) VALUES
(3, 2, 1541034241, 1541034241, 0, 0, 0, 0, 1, 3, 'tt_content', 'assets', 1, NULL, NULL, NULL, '', '{\"default\":{\"cropArea\":{\"height\":1,\"width\":0.999,\"x\":0,\"y\":0},\"selectedRatio\":\"NaN\",\"focusArea\":null}}', 0, NULL);
INSERT INTO `sys_file_reference` (`uid`, `pid`, `tstamp`, `crdate`, `deleted`, `hidden`, `sys_language_uid`, `l10n_parent`, `uid_local`, `uid_foreign`, `tablenames`, `fieldname`, `sorting_foreign`, `title`, `description`, `alternative`, `link`, `crop`, `autoplay`, `l10n_state`) VALUES
(4, 3, 1541034241, 1541034241, 0, 0, 0, 0, 2, 4, 'tt_content', 'assets', 1, NULL, NULL, NULL, '', '', 0, NULL);
INSERT INTO `sys_file_reference` (`uid`, `pid`, `tstamp`, `crdate`, `deleted`, `hidden`, `sys_language_uid`, `l10n_parent`, `uid_local`, `uid_foreign`, `tablenames`, `fieldname`, `sorting_foreign`, `title`, `description`, `alternative`, `link`, `crop`, `autoplay`, `l10n_state`) VALUES
(5, 4, 1621764154,1621764143, 0, 0, 0, 0, 3, 5, 'tt_content', 'assets', 1, NULL, NULL, NULL, '', '', 0, NULL);
