name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-18.04
    name: Linting
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          tools: composer:v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: dependencies-composer-${{ runner.os }}-${{ hashFiles('composer.json') }}
      - name: Add GITHUB_TOKEN if available
        run: if [ -n "${{secrets.GITHUB_TOKEN}}" ]; then composer config github-oauth.github.com ${{secrets.GITHUB_TOKEN}}; fi;
      - name: Install composer dependencies
        run: |
          rm -f composer.lock
          composer require typo3/minimal:^11.0
      - name: phpstan
        run: composer phpstan
      - name: PHPCS
        run: composer php:lint
      - name: Typoscript Linter
        run: composer ts:lint

  build_doc:
    runs-on: ubuntu-18.04
    name: Build documentation
    steps:
      - uses: actions/checkout@v2
      - name: Build doc
        run: composer build:doc

  tests:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        env:
          - { php: 8.1, TYPO3_VERSION: ^11.0 }
          - { php: 8.0, TYPO3_VERSION: ^11.0 }
          - { php: 7.4, TYPO3_VERSION: ^11.0 }
          - { php: 7.4, TYPO3_VERSION: ^10.4 }
    name: Tests on TYPO3 ${{ matrix.env.TYPO3_VERSION }} / PHP${{ matrix.env.php }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.env.php }}
          tools: composer:v2
          coverage: none
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: dependencies-composer-${{ runner.os }}-${{ hashFiles('composer.json') }}
      - name: Add GITHUB_TOKEN if available
        run: if [ -n "${{secrets.GITHUB_TOKEN}}" ]; then composer config github-oauth.github.com ${{secrets.GITHUB_TOKEN}}; fi;
      - name: Install composer dependencies
        run: |
          rm -f composer.lock
          composer require typo3/minimal:${{ matrix.env.TYPO3_VERSION }}
      - name: Start builtin PHP webserver
        run: |
          php -S 127.0.0.1:8888 -t .Build/public/ &>/dev/null &
          sleep 2
      - uses: nanasess/setup-chromedriver@master
      - name: Start chromedriver
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          sleep 2
      - name: Unit tests (TYPO3 ${{ matrix.env.TYPO3_VERSION }} with PHP${{ matrix.env.php }})
        run: composer tests:unit
      - name: Acceptance tests (TYPO3 ${{ matrix.env.TYPO3_VERSION }} with PHP${{ matrix.env.php }})
        env:
          # TYPO3_PATH_ROOT: $GITHUB_WORKSPACE/.Build/public
          typo3DatabaseDriver: pdo_sqlite
          CHROME_OPTION_1: "--headless"
        run: |
          composer tests:acceptance
